"""
Orchestrator entrypoint — PR-time nudge workflow.

Called by the GitHub Actions workflow when a PR is opened or updated.
Matches PR changed files against triaged issues' affected_paths and posts
an informational nudge comment when overlaps are found.
"""

import json
import logging
import os
import re
import sys
from typing import Any

from orchestrator.github_client import GitHubClient, DEFAULT_MARKER

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

# Marker for the PR nudge comment (distinct from the triage marker).
PR_NUDGE_MARKER = "<!-- devin-pr-nudge:v1 -->"

# Max issues to show in the nudge comment before truncating.
MAX_MATCHES = 5


# ---------------------------------------------------------------------------
# Fixability gate
# ---------------------------------------------------------------------------

def is_fixable(card: dict[str, Any]) -> bool:
    """Return True if a triage card qualifies for the auto-fix checkbox.

    Criteria:
    - Classification is 'bug' (not unclear, question, or feature-request).
    - No outstanding clarification questions.
    - Confidence >= 0.7.
    """
    return (
        card.get("classification") == "bug"
        and not card.get("questions")
        and (card.get("confidence", 0) >= 0.7)
    )


# ---------------------------------------------------------------------------
# Card extraction from issue comments
# ---------------------------------------------------------------------------

def _extract_card_from_comment(body: str) -> dict[str, Any] | None:
    """Extract the triage card JSON embedded in an HTML comment.

    Looks for the pattern: <!-- devin-triage:v1\n{...json...}\n-->
    """
    pattern = r"<!--\s*devin-triage:v1\s*\n(.*?)\n\s*-->"
    match = re.search(pattern, body, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(1).strip())
    except (json.JSONDecodeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# Path matching
# ---------------------------------------------------------------------------

def _match_paths(
    pr_files: list[str], affected_paths: list[str]
) -> list[str]:
    """Return PR files that overlap with triage-card affected_paths.

    A match occurs when:
    - A PR file exactly equals an affected path, OR
    - A PR file starts with an affected path (prefix/directory match).
    """
    matched: list[str] = []
    for pr_file in pr_files:
        for affected in affected_paths:
            if pr_file == affected or pr_file.startswith(affected.rstrip("/") + "/"):
                if pr_file not in matched:
                    matched.append(pr_file)
                break
    return matched


# ---------------------------------------------------------------------------
# Comment rendering
# ---------------------------------------------------------------------------

def _render_nudge_comment(matches: list[dict[str, Any]]) -> str:
    """Render a list of matched issues into a PR nudge comment.

    Each entry in *matches* has:
      - issue_number, issue_title, classification, priority, confidence,
        summary, matched_files (list[str]), fixable (bool)
    """
    lines: list[str] = []
    lines.append("## 🔔 PR Nudge — Related Triaged Issues")
    lines.append("")
    lines.append(
        "This PR touches code linked to the following triaged issues. "
        "Consider fixing while you're in this area."
    )
    lines.append("")

    shown = matches[:MAX_MATCHES]
    for m in shown:
        lines.append(
            f"### #{m['issue_number']}: {m['issue_title']}"
        )
        lines.append(
            f"**Classification:** `{m['classification']}` | "
            f"**Priority:** `{m['priority']}` | "
            f"**Confidence:** `{m.get('confidence', '?')}`"
        )
        lines.append(f"> {m['summary']}")
        lines.append("")
        lines.append("**Overlapping files:**")
        for f in m["matched_files"]:
            lines.append(f"- `{f}`")
        lines.append("")

        # Auto-fix checkbox — only for qualifying bugs
        if m.get("fixable"):
            lines.append(
                f"- [ ] **Attempt auto-fix for #{m['issue_number']}** with Devin"
            )
            lines.append("")

    remaining = len(matches) - MAX_MATCHES
    if remaining > 0:
        lines.append(f"…and **{remaining}** more matched issue(s).")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Devin PR Nudge (v1.0)*")
    lines.append("")
    lines.append(f"{PR_NUDGE_MARKER}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main orchestration
# ---------------------------------------------------------------------------


def nudge_pr(
    *,
    repo: str,
    pr_number: int,
) -> None:
    """End-to-end PR nudge flow.

    1. Get PR changed files.
    2. List open issues with 'devin:triaged' label.
    3. Parse triage card from each issue's bot comment.
    4. Match affected_paths against PR files.
    5. Post/update nudge comment if matches found.
    """
    gh = GitHubClient()

    # --- 1. PR changed files ----------------------------------------------
    pr_files = gh.get_pr_changed_files(repo, pr_number)
    logger.info("PR #%d has %d changed file(s).", pr_number, len(pr_files))
    if not pr_files:
        logger.info("No changed files — nothing to match.")
        return

    # --- 2. Triaged issues ------------------------------------------------
    issues = gh.list_issues(repo, labels=["devin:triaged"], state="open")
    logger.info("Found %d open triaged issue(s).", len(issues))
    if not issues:
        logger.info("No triaged issues — nothing to match.")
        return

    # --- 3+4. Parse cards & match -----------------------------------------
    matches: list[dict[str, Any]] = []
    for issue in issues:
        issue_number = issue["number"]
        issue_title = issue["title"]

        # Find the bot's triage comment.
        comments = gh.get_issue_comments(repo, issue_number)
        card = None
        for c in comments:
            body = c.get("body", "")
            if DEFAULT_MARKER in body:
                card = _extract_card_from_comment(body)
                break

        if card is None:
            logger.debug("Issue #%d: no triage card found, skipping.", issue_number)
            continue

        affected_paths = card.get("affected_paths", [])
        if not affected_paths:
            continue

        matched_files = _match_paths(pr_files, affected_paths)
        if matched_files:
            matches.append(
                {
                    "issue_number": issue_number,
                    "issue_title": issue_title,
                    "classification": card.get("classification", "unknown"),
                    "priority": card.get("suggested_priority", "unset"),
                    "confidence": card.get("confidence", 0),
                    "summary": card.get("summary", ""),
                    "matched_files": matched_files,
                    "fixable": is_fixable(card),
                }
            )

    # --- 5. Post nudge comment --------------------------------------------
    if not matches:
        logger.info("No matches between PR files and triaged issues.")
        return

    logger.info(
        "Found %d triaged issue(s) matching PR #%d.", len(matches), pr_number
    )
    comment_body = _render_nudge_comment(matches)
    gh.upsert_comment(repo, pr_number, PR_NUDGE_MARKER, comment_body)
    logger.info("Nudge comment posted/updated on PR #%d.", pr_number)


# ---------------------------------------------------------------------------
# CLI / GitHub Actions entry
# ---------------------------------------------------------------------------


def main() -> None:
    """Parse environment variables (set by the GitHub Actions workflow) and run."""
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    pr_number_str = os.environ.get("PR_NUMBER", "")

    if not repo or not pr_number_str:
        print(
            "Error: GITHUB_REPOSITORY and PR_NUMBER must be set.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        pr_number = int(pr_number_str)
    except ValueError:
        print(
            f"Error: PR_NUMBER must be an integer, got '{pr_number_str}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    nudge_pr(repo=repo, pr_number=pr_number)


if __name__ == "__main__":
    main()
