"""
Orchestrator entrypoint — Issue Triage workflow.

Called by the GitHub Actions workflow with the issue payload.
Wires together: Devin client → validation → GitHub client.
"""

import json
import logging
import os
import sys
from typing import Any

from orchestrator.devin_client import DevinClient
from orchestrator.github_client import GitHubClient, DEFAULT_MARKER
from orchestrator.prompt_builder import build_triage_prompt
from orchestrator.validation import validate_triage_card

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------

_TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "templates", "triage_comment.md")


def _render_comment(card: dict[str, Any]) -> str:
    """Render a triage card dict into a Markdown comment body.

    Uses Jinja-style template from Story 2.  We do simple str.replace to avoid
    pulling in Jinja2 as a dependency (keeping footprint light for the PoC).
    """
    json_str = json.dumps(card, indent=2)

    # --- build sections ---
    summary = card.get("summary", "")
    classification = card.get("classification", "unknown")
    priority = card.get("suggested_priority", "unset")
    confidence = card.get("confidence", 0)
    confidence_pct = round(confidence * 100)

    questions = card.get("questions", [])
    affected_paths = card.get("affected_paths", [])

    lines: list[str] = []
    lines.append("## 🤖 Devin Triage Intelligence")
    lines.append("")
    lines.append(f"**Summary:** {summary}")
    lines.append("")
    lines.append(
        f"**Classification:** `{classification}` | "
        f"**Priority:** `{priority}` | "
        f"**Confidence:** `{confidence_pct}%`"
    )

    if questions:
        lines.append("")
        lines.append("### 🔍 Clarification Questions")
        for q in questions:
            lines.append(f"- [ ] {q}")

    if affected_paths:
        lines.append("")
        lines.append("### 📂 Likely Affected Paths")
        for p in affected_paths:
            lines.append(f"- `{p}`")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by Devin (v1.0)*")
    lines.append("")
    lines.append(f"<!-- devin-triage:v1\n{json_str}\n-->")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Devin output parsing
# ---------------------------------------------------------------------------


def _extract_triage_card(session_data: dict[str, Any]) -> dict[str, Any] | None:
    """Try to extract a valid triage card JSON from the Devin session result.

    Checks, in order:
    1. ``structured_output`` field (if Devin returns structured JSON).
    2. The last message in the conversation that parses as JSON.
    """
    # 1. Structured output (preferred)
    structured = session_data.get("structured_output")
    if isinstance(structured, dict) and validate_triage_card(structured):
        return structured

    # 2. Scan conversation for a JSON blob
    for item in reversed(session_data.get("conversation", [])):
        text = item.get("message", "") if isinstance(item, dict) else ""
        try:
            # Try to find JSON in the message (may be wrapped in markdown fences)
            json_text = text
            if "```json" in json_text:
                json_text = json_text.split("```json", 1)[1].split("```", 1)[0]
            elif "```" in json_text:
                json_text = json_text.split("```", 1)[1].split("```", 1)[0]

            candidate = json.loads(json_text.strip())
            if isinstance(candidate, dict) and validate_triage_card(candidate):
                return candidate
        except (json.JSONDecodeError, IndexError, KeyError):
            continue

    return None


# ---------------------------------------------------------------------------
# Main orchestration
# ---------------------------------------------------------------------------


def triage_issue(
    *,
    repo: str,
    issue_number: int,
    issue_title: str,
    issue_body: str,
    devin_timeout: int = 600,
) -> None:
    """End-to-end triage flow for a single GitHub issue.

    1. Build prompt.
    2. Start Devin session + poll to completion.
    3. Validate output against schema.
    4. Post/update comment on the issue.
    5. Apply labels.
    """
    logger.info("Triaging %s#%d — %s", repo, issue_number, issue_title)

    # --- Clients ----------------------------------------------------------
    devin = DevinClient()  # reads DEVIN_API_KEY from env
    gh = GitHubClient()    # reads GITHUB_TOKEN from env

    # --- 1. Prompt --------------------------------------------------------
    prompt = build_triage_prompt(
        repo=repo,
        issue_number=issue_number,
        issue_title=issue_title,
        issue_body=issue_body,
    )
    logger.info("Prompt built (%d chars).", len(prompt))

    # --- 2. Devin session -------------------------------------------------
    session_id = devin.create_session(prompt)
    logger.info("Devin session started: %s", session_id)

    session_data = devin.poll_session(session_id, timeout=devin_timeout)
    status = session_data.get("status_enum", session_data.get("status"))
    logger.info("Devin session ended with status: %s", status)

    # Handle 'blocked' — Devin is asking for human input / confirmation.
    # Send a nudge telling it to proceed autonomously, then re-poll.
    MAX_UNBLOCK_ATTEMPTS = 2
    unblock_count = 0
    while status == "blocked" and unblock_count < MAX_UNBLOCK_ATTEMPTS:
        unblock_count += 1
        logger.info(
            "Devin is blocked (attempt %d/%d). Sending nudge.",
            unblock_count,
            MAX_UNBLOCK_ATTEMPTS,
        )
        devin.send_message(
            session_id,
            (
                "Do not wait for my input. You are running in fully autonomous "
                "mode. Proceed with your best judgement and return the JSON "
                "triage card as described in the original prompt. If anything "
                "is unclear, set classification to 'unclear' and put your "
                "questions in the questions array — but still return the JSON."
            ),
        )
        session_data = devin.poll_session(session_id, timeout=devin_timeout)
        status = session_data.get("status_enum", session_data.get("status"))
        logger.info("Devin session status after nudge: %s", status)

    # --- 3. Extract & validate --------------------------------------------
    card = _extract_triage_card(session_data)

    if card is None:
        logger.warning("Could not extract a valid triage card from Devin output.")
        # Log Devin conversation for diagnostics
        conversation = session_data.get("conversation", [])
        logger.info("Session had %d conversation messages.", len(conversation))
        for i, msg in enumerate(conversation[-5:]):  # last 5 messages
            role = msg.get("role", "?") if isinstance(msg, dict) else "?"
            text = msg.get("message", "")[:300] if isinstance(msg, dict) else str(msg)[:300]
            logger.info("  [%d] %s: %s", i, role, text)
        # Post a fallback comment so the issue isn't silently ignored.
        fallback_body = (
            "## 🤖 Devin Triage Intelligence\n\n"
            "⚠️ Devin was unable to produce a valid triage card for this issue.\n"
            f"Session status: `{status}`.\n\n"
            "A human reviewer should triage this issue manually.\n\n"
            "---\n*Generated by Devin (v1.0)*"
        )
        gh.upsert_comment(repo, issue_number, DEFAULT_MARKER, fallback_body)
        gh.add_labels(repo, issue_number, ["needs-info"])
        return

    logger.info("Valid triage card extracted: %s", card.get("classification"))

    # --- 4. Post comment --------------------------------------------------
    comment_body = _render_comment(card)
    gh.upsert_comment(repo, issue_number, DEFAULT_MARKER, comment_body)
    logger.info("Comment posted/updated on %s#%d.", repo, issue_number)

    # --- 5. Labels --------------------------------------------------------
    labels_to_add: list[str] = []

    classification = card.get("classification")
    questions = card.get("questions", [])

    if classification == "unclear" or questions:
        labels_to_add.append("needs-info")
    else:
        labels_to_add.append("devin:triaged")

    # Add any labels Devin suggested (if they seem reasonable)
    for label in card.get("suggested_labels", []):
        if label not in labels_to_add:
            labels_to_add.append(label)

    if labels_to_add:
        gh.add_labels(repo, issue_number, labels_to_add)
        logger.info("Labels applied: %s", labels_to_add)


# ---------------------------------------------------------------------------
# CLI / GitHub Actions entry
# ---------------------------------------------------------------------------


def main() -> None:
    """Parse environment variables (set by the GitHub Actions workflow) and run."""
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    issue_number_str = os.environ.get("ISSUE_NUMBER", "")
    issue_title = os.environ.get("ISSUE_TITLE", "")
    issue_body = os.environ.get("ISSUE_BODY", "")

    if not repo or not issue_number_str:
        print("Error: GITHUB_REPOSITORY and ISSUE_NUMBER must be set.", file=sys.stderr)
        sys.exit(1)

    try:
        issue_number = int(issue_number_str)
    except ValueError:
        print(f"Error: ISSUE_NUMBER must be an integer, got '{issue_number_str}'.", file=sys.stderr)
        sys.exit(1)

    triage_issue(
        repo=repo,
        issue_number=issue_number,
        issue_title=issue_title,
        issue_body=issue_body,
    )


if __name__ == "__main__":
    main()
