"""
Unit tests for orchestrator.devin_fix — Story 7.

Auto-fix is now triggered from a PR nudge comment (not triage comment).
All external calls (Devin, GitHub) are mocked.
"""

import json
import unittest
from unittest.mock import MagicMock, patch, PropertyMock

from orchestrator.devin_fix import (
    detect_ticked_issues,
    extract_card_from_comment,
    fetch_triage_card,
    _render_success_section,
    _render_failure_section,
    _update_nudge_comment_with_result,
    attempt_fix,
    LABEL_FIX_ATTEMPTED,
    LABEL_FIX_FAILED,
)
from orchestrator.github_client import DEFAULT_MARKER
from orchestrator.pr_nudge import PR_NUDGE_MARKER


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

VALID_CARD = {
    "schema_version": "v1",
    "classification": "bug",
    "confidence": 0.92,
    "summary": "Off-by-one in /summary endpoint.",
    "questions": [],
    "affected_paths": ["demo_app/services/stats_service.py"],
    "suggested_labels": ["bug"],
    "suggested_priority": "medium",
}


def _make_nudge_body(*issue_numbers, ticked=None):
    """Build a realistic PR nudge comment body with checkboxes.

    Args:
        issue_numbers: Issue numbers to include.
        ticked: Set of issue numbers whose checkbox is ticked.
    """
    ticked = ticked or set()
    lines = [
        "## 🔔 PR Nudge — Related Triaged Issues",
        "",
        "This PR touches code linked to the following triaged issues.",
        "",
    ]
    for n in issue_numbers:
        lines.append(f"### #{n}: Bug #{n}")
        lines.append(f"**Classification:** `bug` | **Priority:** `high` | **Confidence:** `0.9`")
        lines.append(f"> Summary for issue #{n}")
        lines.append("")
        lines.append("**Overlapping files:**")
        lines.append(f"- `demo_app/services/stats_service.py`")
        lines.append("")
        state = "x" if n in ticked else " "
        lines.append(f"- [{state}] **Attempt auto-fix for #{n}** with Devin")
        lines.append("")
    lines.append("---")
    lines.append("*Generated by Devin PR Nudge (v1.0)*")
    lines.append("")
    lines.append(PR_NUDGE_MARKER)
    return "\n".join(lines)


def _make_triage_comment(card=None):
    """Build a triage comment with embedded card JSON."""
    card = card or VALID_CARD
    return (
        f"{DEFAULT_MARKER}\n\n## Triage Card\n\n"
        f"<!-- devin-triage:v1\n{json.dumps(card)}\n-->"
    )


# ---------------------------------------------------------------------------
# detect_ticked_issues
# ---------------------------------------------------------------------------


class TestDetectTickedIssues(unittest.TestCase):

    def test_single_checkbox_ticked(self):
        old = _make_nudge_body(2, 3, ticked=set())
        new = _make_nudge_body(2, 3, ticked={2})
        self.assertEqual(detect_ticked_issues(old, new), [2])

    def test_multiple_checkboxes_ticked(self):
        old = _make_nudge_body(2, 3, ticked=set())
        new = _make_nudge_body(2, 3, ticked={2, 3})
        self.assertEqual(detect_ticked_issues(old, new), [2, 3])

    def test_already_ticked_no_change(self):
        old = _make_nudge_body(2, 3, ticked={2})
        new = _make_nudge_body(2, 3, ticked={2})
        self.assertEqual(detect_ticked_issues(old, new), [])

    def test_none_ticked(self):
        old = _make_nudge_body(2, 3, ticked=set())
        new = _make_nudge_body(2, 3, ticked=set())
        self.assertEqual(detect_ticked_issues(old, new), [])

    def test_no_checkboxes_at_all(self):
        old = "Just a normal comment."
        new = "Just a normal comment, edited."
        self.assertEqual(detect_ticked_issues(old, new), [])

    def test_one_already_ticked_another_newly_ticked(self):
        old = _make_nudge_body(2, 3, ticked={2})
        new = _make_nudge_body(2, 3, ticked={2, 3})
        self.assertEqual(detect_ticked_issues(old, new), [3])


# ---------------------------------------------------------------------------
# extract_card_from_comment
# ---------------------------------------------------------------------------


class TestExtractCard(unittest.TestCase):

    def test_extracts_valid_card(self):
        body = _make_triage_comment()
        card = extract_card_from_comment(body)
        self.assertIsNotNone(card)
        self.assertEqual(card["classification"], "bug")

    def test_returns_none_without_marker(self):
        self.assertIsNone(extract_card_from_comment("No card here."))

    def test_returns_none_for_corrupt_json(self):
        body = "<!-- devin-triage:v1\n{not json}\n-->"
        self.assertIsNone(extract_card_from_comment(body))


# ---------------------------------------------------------------------------
# Render helpers
# ---------------------------------------------------------------------------


class TestRenderSections(unittest.TestCase):

    def test_success_section_contains_issue_and_pr_url(self):
        section = _render_success_section(2, "https://github.com/owner/repo/pull/42")
        self.assertIn("✅ Auto-fix for #2", section)
        self.assertIn("https://github.com/owner/repo/pull/42", section)

    def test_failure_section_contains_issue_and_pointer(self):
        session_data = {
            "messages": [
                {"type": "devin_message", "message": "I tried to fix it by changing the off-by-one logic but tests still fail."},
            ],
        }
        section = _render_failure_section(3, session_data)
        self.assertIn("❌ Auto-fix failed for #3", section)
        self.assertIn("off-by-one", section)
        self.assertIn("manual investigation", section)

    def test_failure_section_handles_no_messages(self):
        section = _render_failure_section(5, {"messages": []})
        self.assertIn("❌ Auto-fix failed for #5", section)
        self.assertIn("manual investigation", section)


# ---------------------------------------------------------------------------
# _update_nudge_comment_with_result
# ---------------------------------------------------------------------------


class TestUpdateNudgeComment(unittest.TestCase):

    def test_appends_result_section(self):
        gh = MagicMock()
        body = _make_nudge_body(2, ticked={2})
        result = "\n\n### ✅ Auto-fix for #2\nPR link here."

        _update_nudge_comment_with_result(gh, "owner/repo", 10, body, 2, result)

        gh.upsert_comment.assert_called_once()
        updated = gh.upsert_comment.call_args[0][3]
        self.assertIn("✅ Auto-fix for #2", updated)
        self.assertIn("PR link here.", updated)

    def test_replaces_previous_result_for_same_issue(self):
        gh = MagicMock()
        body = _make_nudge_body(2, ticked={2}) + "\n\n### ❌ Auto-fix failed for #2\nOld failure text."
        result = "\n\n### ✅ Auto-fix for #2\nNew PR link."

        _update_nudge_comment_with_result(gh, "owner/repo", 10, body, 2, result)

        updated = gh.upsert_comment.call_args[0][3]
        self.assertNotIn("❌ Auto-fix failed for #2", updated)
        self.assertIn("✅ Auto-fix for #2", updated)


# ---------------------------------------------------------------------------
# attempt_fix (end-to-end, mocked)
# ---------------------------------------------------------------------------


class TestAttemptFix(unittest.TestCase):
    """Full flow with mocked Devin and GitHub clients (PR nudge context)."""

    def _mock_pr_response(self, pr_url=None):
        resp = MagicMock()
        resp.raise_for_status.return_value = None
        if pr_url:
            resp.json.return_value = [{"html_url": pr_url}]
        else:
            resp.json.return_value = []
        return resp

    def _mock_issue_response(self, title="Off-by-one", body="Count is wrong."):
        resp = MagicMock()
        resp.raise_for_status.return_value = None
        resp.json.return_value = {"title": title, "body": body}
        return resp

    @patch("orchestrator.devin_fix.GitHubClient")
    @patch("orchestrator.devin_fix.DevinClient")
    def test_success_flow_posts_pr_link_on_nudge(self, MockDevin, MockGH):
        devin = MockDevin.return_value
        devin.create_session.return_value = "sess-fix-1"
        devin.poll_session.return_value = {
            "status_enum": "finished",
            "messages": [],
        }

        gh = MockGH.return_value
        gh.base_url = "https://api.github.com"

        # fetch_triage_card returns VALID_CARD from issue #2's comments
        gh.get_issue_comments.return_value = [
            {"body": _make_triage_comment(VALID_CARD)},
        ]
        # Fetch issue details + find fix PR
        gh._session.get.side_effect = [
            self._mock_issue_response(),
            self._mock_pr_response("https://github.com/owner/repo/pull/42"),
        ]

        comment_body = _make_nudge_body(2, ticked={2})

        attempt_fix(
            repo="owner/repo",
            pr_number=10,
            issue_number=2,
            comment_body=comment_body,
        )

        # Verify nudge comment was updated with success
        gh.upsert_comment.assert_called_once()
        updated = gh.upsert_comment.call_args[0][3]
        self.assertIn("✅ Auto-fix for #2", updated)
        self.assertIn("pull/42", updated)

        # Verify fix-attempted label on the issue
        gh.add_labels.assert_called_once()
        labels = gh.add_labels.call_args[0][2]
        self.assertIn(LABEL_FIX_ATTEMPTED, labels)

    @patch("orchestrator.devin_fix.GitHubClient")
    @patch("orchestrator.devin_fix.DevinClient")
    def test_failure_flow_posts_pointers_on_nudge(self, MockDevin, MockGH):
        devin = MockDevin.return_value
        devin.create_session.return_value = "sess-fix-2"
        devin.poll_session.return_value = {
            "status_enum": "finished",
            "messages": [
                {"type": "devin_message", "message": "I could not reproduce the bug after multiple attempts."},
            ],
        }

        gh = MockGH.return_value
        gh.base_url = "https://api.github.com"

        gh.get_issue_comments.return_value = [
            {"body": _make_triage_comment(VALID_CARD)},
        ]
        gh._session.get.side_effect = [
            self._mock_issue_response(),
            self._mock_pr_response(None),  # No PR found
        ]

        comment_body = _make_nudge_body(2, ticked={2})

        attempt_fix(
            repo="owner/repo",
            pr_number=10,
            issue_number=2,
            comment_body=comment_body,
        )

        # Verify nudge comment was updated with failure
        gh.upsert_comment.assert_called_once()
        updated = gh.upsert_comment.call_args[0][3]
        self.assertIn("❌ Auto-fix failed for #2", updated)

        # Verify fix-failed label on the issue
        gh.add_labels.assert_called_once()
        labels = gh.add_labels.call_args[0][2]
        self.assertIn(LABEL_FIX_FAILED, labels)

    @patch("orchestrator.devin_fix.GitHubClient")
    @patch("orchestrator.devin_fix.DevinClient")
    def test_aborts_when_no_triage_card_on_issue(self, MockDevin, MockGH):
        """If the issue has no triage card, do nothing."""
        gh = MockGH.return_value
        gh.get_issue_comments.return_value = [
            {"body": "Regular human comment, no card."},
        ]

        attempt_fix(
            repo="owner/repo",
            pr_number=10,
            issue_number=2,
            comment_body=_make_nudge_body(2, ticked={2}),
        )

        # Devin should never be called
        MockDevin.return_value.create_session.assert_not_called()


# ---------------------------------------------------------------------------
# Fix prompt builder
# ---------------------------------------------------------------------------


class TestFixPromptBuilder(unittest.TestCase):

    def test_prompt_contains_issue_context(self):
        from orchestrator.fix_prompt_builder import build_fix_prompt

        prompt = build_fix_prompt(
            repo="owner/repo",
            issue_number=2,
            issue_title="Off-by-one",
            issue_body="Count is wrong.",
            triage_card=VALID_CARD,
        )
        self.assertIn("owner/repo", prompt)
        self.assertIn("#2", prompt)
        self.assertIn("Off-by-one", prompt)
        self.assertIn("stats_service.py", prompt)
        self.assertIn("devin/fix-issue-2", prompt)

    def test_prompt_includes_autonomous_instruction(self):
        from orchestrator.fix_prompt_builder import build_fix_prompt

        prompt = build_fix_prompt(
            repo="owner/repo",
            issue_number=2,
            issue_title="Test",
            issue_body="Body.",
            triage_card=VALID_CARD,
        )
        self.assertIn("fully autonomous mode", prompt)

    def test_prompt_includes_test_suite_step(self):
        from orchestrator.fix_prompt_builder import build_fix_prompt

        prompt = build_fix_prompt(
            repo="owner/repo",
            issue_number=2,
            issue_title="Test",
            issue_body="Body.",
            triage_card=VALID_CARD,
        )
        self.assertIn("pytest", prompt)
        self.assertIn("reproduction test", prompt)


if __name__ == "__main__":
    unittest.main()
