"""
Unit tests for orchestrator.devin_fix — Story 7.

All external calls (Devin, GitHub) are mocked.
"""

import json
import unittest
from unittest.mock import MagicMock, patch, PropertyMock

from orchestrator.devin_fix import (
    checkbox_was_ticked,
    extract_card_from_comment,
    _render_success_section,
    _render_failure_section,
    _update_comment_with_result,
    attempt_fix,
    LABEL_FIX_ATTEMPTED,
    LABEL_FIX_FAILED,
)
from orchestrator.github_client import DEFAULT_MARKER


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

VALID_CARD = {
    "schema_version": "v1",
    "classification": "bug",
    "confidence": 0.92,
    "summary": "Off-by-one in /summary endpoint.",
    "questions": [],
    "affected_paths": ["demo_app/services/stats_service.py"],
    "suggested_labels": ["bug"],
    "suggested_priority": "medium",
}


def _make_comment_body(card=None, checked=False):
    """Build a realistic triage comment body."""
    card = card or VALID_CARD
    checkbox = "- [x] Attempt auto-fix with Devin" if checked else "- [ ] Attempt auto-fix with Devin"
    return (
        "## 🤖 Devin Triage Intelligence\n\n"
        f"**Summary:** {card['summary']}\n\n"
        "### 🔧 Auto-fix\n"
        f"{checkbox}\n\n"
        "---\n"
        "*Generated by Devin (v1.0)*\n\n"
        f"<!-- devin-triage:v1\n{json.dumps(card)}\n-->"
    )


# ---------------------------------------------------------------------------
# checkbox_was_ticked
# ---------------------------------------------------------------------------


class TestCheckboxDetection(unittest.TestCase):

    def test_unchecked_to_checked(self):
        old = _make_comment_body(checked=False)
        new = _make_comment_body(checked=True)
        self.assertTrue(checkbox_was_ticked(old, new))

    def test_already_checked_no_change(self):
        old = _make_comment_body(checked=True)
        new = _make_comment_body(checked=True)
        self.assertFalse(checkbox_was_ticked(old, new))

    def test_unchecked_stays_unchecked(self):
        old = _make_comment_body(checked=False)
        new = _make_comment_body(checked=False)
        self.assertFalse(checkbox_was_ticked(old, new))

    def test_no_checkbox_at_all(self):
        old = "Just a normal comment."
        new = "Just a normal comment, edited."
        self.assertFalse(checkbox_was_ticked(old, new))


# ---------------------------------------------------------------------------
# extract_card_from_comment
# ---------------------------------------------------------------------------


class TestExtractCard(unittest.TestCase):

    def test_extracts_valid_card(self):
        body = _make_comment_body()
        card = extract_card_from_comment(body)
        self.assertIsNotNone(card)
        self.assertEqual(card["classification"], "bug")

    def test_returns_none_without_marker(self):
        self.assertIsNone(extract_card_from_comment("No card here."))

    def test_returns_none_for_corrupt_json(self):
        body = "<!-- devin-triage:v1\n{not json}\n-->"
        self.assertIsNone(extract_card_from_comment(body))


# ---------------------------------------------------------------------------
# Render helpers
# ---------------------------------------------------------------------------


class TestRenderSections(unittest.TestCase):

    def test_success_section_contains_pr_url(self):
        section = _render_success_section("https://github.com/owner/repo/pull/42")
        self.assertIn("✅ Auto-fix attempted", section)
        self.assertIn("https://github.com/owner/repo/pull/42", section)

    def test_failure_section_contains_pointer(self):
        session_data = {
            "messages": [
                {"type": "devin_message", "message": "I tried to fix it by changing the off-by-one logic but tests still fail."},
            ],
        }
        section = _render_failure_section(session_data)
        self.assertIn("❌ Auto-fix failed", section)
        self.assertIn("off-by-one", section)
        self.assertIn("manual investigation", section)

    def test_failure_section_handles_no_messages(self):
        section = _render_failure_section({"messages": []})
        self.assertIn("❌ Auto-fix failed", section)
        self.assertIn("manual investigation", section)


# ---------------------------------------------------------------------------
# _update_comment_with_result
# ---------------------------------------------------------------------------


class TestUpdateCommentWithResult(unittest.TestCase):

    def test_appends_result_section(self):
        gh = MagicMock()
        body = _make_comment_body()
        result = "\n\n### ✅ Auto-fix attempted\nPR link here."

        _update_comment_with_result(gh, "owner/repo", 1, body, result)

        gh.upsert_comment.assert_called_once()
        updated = gh.upsert_comment.call_args[0][3]
        self.assertIn("✅ Auto-fix attempted", updated)
        self.assertIn("PR link here.", updated)

    def test_replaces_previous_result_section(self):
        gh = MagicMock()
        body = _make_comment_body() + "\n\n### ❌ Auto-fix failed\nOld failure text."
        result = "\n\n### ✅ Auto-fix attempted\nNew PR link."

        _update_comment_with_result(gh, "owner/repo", 1, body, result)

        updated = gh.upsert_comment.call_args[0][3]
        self.assertNotIn("❌ Auto-fix failed", updated)
        self.assertIn("✅ Auto-fix attempted", updated)


# ---------------------------------------------------------------------------
# attempt_fix (end-to-end, mocked)
# ---------------------------------------------------------------------------


class TestAttemptFix(unittest.TestCase):

    def _mock_pr_response(self, pr_url=None):
        resp = MagicMock()
        resp.raise_for_status.return_value = None
        if pr_url:
            resp.json.return_value = [{"html_url": pr_url}]
        else:
            resp.json.return_value = []
        return resp

    @patch("orchestrator.devin_fix.GitHubClient")
    @patch("orchestrator.devin_fix.DevinClient")
    def test_success_flow_posts_pr_link(self, MockDevin, MockGH):
        devin = MockDevin.return_value
        devin.create_session.return_value = "sess-fix-1"
        devin.poll_session.return_value = {
            "status_enum": "finished",
            "messages": [],
        }

        gh = MockGH.return_value
        # _find_fix_pr uses gh._session.get
        gh._session.get.return_value = self._mock_pr_response(
            "https://github.com/owner/repo/pull/42"
        )
        gh.base_url = "https://api.github.com"

        comment_body = _make_comment_body(checked=True)

        attempt_fix(
            repo="owner/repo",
            issue_number=2,
            issue_title="Off-by-one",
            issue_body="Count is wrong.",
            comment_body=comment_body,
        )

        # Verify comment was updated with success
        gh.upsert_comment.assert_called_once()
        updated = gh.upsert_comment.call_args[0][3]
        self.assertIn("✅ Auto-fix attempted", updated)
        self.assertIn("pull/42", updated)

        # Verify fix-attempted label
        gh.add_labels.assert_called_once()
        labels = gh.add_labels.call_args[0][2]
        self.assertIn(LABEL_FIX_ATTEMPTED, labels)

    @patch("orchestrator.devin_fix.GitHubClient")
    @patch("orchestrator.devin_fix.DevinClient")
    def test_failure_flow_posts_pointers(self, MockDevin, MockGH):
        devin = MockDevin.return_value
        devin.create_session.return_value = "sess-fix-2"
        devin.poll_session.return_value = {
            "status_enum": "finished",
            "messages": [
                {"type": "devin_message", "message": "I could not reproduce the bug after multiple attempts."},
            ],
        }

        gh = MockGH.return_value
        # No PR found
        gh._session.get.return_value = self._mock_pr_response(None)
        gh.base_url = "https://api.github.com"

        comment_body = _make_comment_body(checked=True)

        attempt_fix(
            repo="owner/repo",
            issue_number=2,
            issue_title="Off-by-one",
            issue_body="Count is wrong.",
            comment_body=comment_body,
        )

        # Verify comment was updated with failure
        gh.upsert_comment.assert_called_once()
        updated = gh.upsert_comment.call_args[0][3]
        self.assertIn("❌ Auto-fix failed", updated)

        # Verify fix-failed label
        gh.add_labels.assert_called_once()
        labels = gh.add_labels.call_args[0][2]
        self.assertIn(LABEL_FIX_FAILED, labels)

    @patch("orchestrator.devin_fix.GitHubClient")
    @patch("orchestrator.devin_fix.DevinClient")
    def test_aborts_when_no_triage_card(self, MockDevin, MockGH):
        """If the comment has no embedded triage card, do nothing."""
        attempt_fix(
            repo="owner/repo",
            issue_number=2,
            issue_title="Test",
            issue_body="Test body.",
            comment_body="Just a plain comment with no card.",
        )

        # Devin should never be called
        MockDevin.return_value.create_session.assert_not_called()


# ---------------------------------------------------------------------------
# Fix prompt builder
# ---------------------------------------------------------------------------


class TestFixPromptBuilder(unittest.TestCase):

    def test_prompt_contains_issue_context(self):
        from orchestrator.fix_prompt_builder import build_fix_prompt

        prompt = build_fix_prompt(
            repo="owner/repo",
            issue_number=2,
            issue_title="Off-by-one",
            issue_body="Count is wrong.",
            triage_card=VALID_CARD,
        )
        self.assertIn("owner/repo", prompt)
        self.assertIn("#2", prompt)
        self.assertIn("Off-by-one", prompt)
        self.assertIn("stats_service.py", prompt)
        self.assertIn("devin/fix-issue-2", prompt)

    def test_prompt_includes_autonomous_instruction(self):
        from orchestrator.fix_prompt_builder import build_fix_prompt

        prompt = build_fix_prompt(
            repo="owner/repo",
            issue_number=2,
            issue_title="Test",
            issue_body="Body.",
            triage_card=VALID_CARD,
        )
        self.assertIn("fully autonomous mode", prompt)

    def test_prompt_includes_test_suite_step(self):
        from orchestrator.fix_prompt_builder import build_fix_prompt

        prompt = build_fix_prompt(
            repo="owner/repo",
            issue_number=2,
            issue_title="Test",
            issue_body="Body.",
            triage_card=VALID_CARD,
        )
        self.assertIn("pytest", prompt)
        self.assertIn("reproduction test", prompt)


if __name__ == "__main__":
    unittest.main()
